DROP TABLE IF EXISTS records;

CREATE TABLE records
(
    record_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service       VARCHAR(255) NOT NULL,
    uri           VARCHAR(255) NOT NULL,
    ip_address    VARCHAR(255) NOT NULL,
    handling_date TIMESTAMP    NOT NULL
);